# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [charlie-moomoo]
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://writes.com.tw/typeface/4257]
